! Command: show running-config
! device: HQ-CORE-SW1 (cEOSLab, EOS-4.35.0F-44178984.4350F (engineering build))
!
no aaa root
!
username hq-admin privilege 15 role network-admin secret sha512 $6$KyoQETEtrsZlf.Vr$CF0UlGOMpcozXJOnkkl3.bEmzirZy5agPDHo7Im5vY01hYp1QoujeYGOV/7KYMx5NzWtMlxppBljhHcwvpdzl0
!
no event-monitor mac
!
no service interface inactive port-id allocation disabled
!
transceiver qsfp default-mode 4x10G
!
service routing protocols model multi-agent
!
agent PowerManager shutdown
agent LedPolicy shutdown
agent Thermostat shutdown
agent PowerFuse shutdown
agent StandbyCpld shutdown
agent LicenseManager shutdown
!
hostname HQ-CORE-SW1
dns domain flyo.local
!
spanning-tree mode rapid-pvst
no spanning-tree vlan-id 4094
spanning-tree edge-port bpduguard default
!
system l1
   unsupported speed action error
   unsupported error-correction action error
!
clock timezone Europe/Budapest
!
vlan 10
   name Management
!
vlan 30
   name Office
!
vlan 100
   name Server
!
vlan 111
   name Native
!
vlan 999
   name BLACKHOLE
   state suspend
!
vlan 1000
   name Guest
!
vlan 4094
   name MLAG-PEER
   trunk group mlagpeer
!
interface Port-Channel1
   description MLAG PEER-LINK
   switchport trunk native vlan 111
   switchport mode trunk
   switchport trunk group mlagpeer
!
interface Port-Channel10
   description MLAG to R1
   switchport trunk native vlan 111
   switchport trunk allowed vlan 1-4093
   switchport mode trunk
   mlag 10
!
interface Port-Channel20
   description MLAG to R2
   switchport trunk native vlan 111
   switchport trunk allowed vlan 1-4093
   switchport mode trunk
   mlag 20
!
interface Port-Channel30
   description Office Interconnect
   switchport trunk native vlan 111
   switchport trunk allowed vlan 1-4093
   switchport mode trunk
!
interface Ethernet1
   description Link to HQ-CORE-R1
   switchport trunk native vlan 111
   switchport trunk allowed vlan 1-4093
   switchport mode trunk
   channel-group 10 mode active
!
interface Ethernet2
   description MLAG PEER-LINK
   switchport trunk native vlan 111
   switchport mode trunk
   channel-group 1 mode active
!
interface Ethernet3
   description MLAG PEER-LINK
   switchport trunk native vlan 111
   switchport mode trunk
   channel-group 1 mode active
!
interface Ethernet4
   description MLAG PEER-LINK
   switchport trunk native vlan 111
   switchport mode trunk
   channel-group 1 mode active
!
interface Ethernet5
   description Link to HQ-OFFICE-SW1
   switchport trunk native vlan 111
   switchport trunk allowed vlan 1-4093
   switchport mode trunk
   channel-group 30 mode active
!
interface Ethernet6
   description Link to HQ-OFFICE-SW2
   switchport trunk native vlan 111
   switchport trunk allowed vlan 1-4093
   switchport mode trunk
   channel-group 30 mode active
!
interface Ethernet7
   description Link to HQ-WINDOWS-SRV
   switchport access vlan 100
   spanning-tree portfast edge
!
interface Ethernet8
   description Link to ADMIN-PC
   switchport access vlan 10
   spanning-tree portfast edge
!
interface Ethernet9
   description UNUSED-PORT
   shutdown
   switchport access vlan 999
   switchport trunk native vlan 111
   switchport trunk allowed vlan 1-4093
!
interface Ethernet10
   description UNUSED-PORT
   shutdown
   switchport access vlan 999
!
interface Ethernet11
   description UNUSED-PORT
   shutdown
   switchport access vlan 999
!
interface Ethernet12
   description Link to HQ-CORE-R2
   switchport trunk native vlan 111
   switchport trunk allowed vlan 1-4093
   switchport mode trunk
   channel-group 20 mode active
!
interface Vlan10
   ip address 10.0.1.4/24
!
interface Vlan4094
   ip address 10.0.95.1/30
!
no ip routing
!
mlag configuration
   domain-id CORE-MLAG
   local-interface Vlan4094
   peer-address 10.0.95.2
   peer-link Port-Channel1
!
ntp local-interface Vlan10
ntp server 10.0.1.1
!
router multicast
   ipv4
      software-forwarding kernel
   !
   ipv6
      software-forwarding kernel
!
end