hostname HQ-FINANCES-SW1
!
boot-start-marker
boot-end-marker
!
!
logging discriminator EXCESS severity drops 6 msg-body drops EXCESSCOLL 
logging buffered 50000
logging console discriminator EXCESS
no aaa new-model
!
!
!
no ip icmp rate-limit unreachable
!         
!         
!
!
!
!
!
!
!
!
ip dhcp snooping
ip audit notify log
ip audit po max-events 100
no ip domain lookup
ip domain name flyo.local
no ip cef
login on-success log
no ipv6 cef
!
!
!
!
!
!
!         
!
crypto pki trustpoint TP-self-signed-2048003
 enrollment selfsigned
 subject-name cn=IOS-Self-Signed-Certificate-2048003
 revocation-check none
 rsakeypair TP-self-signed-2048003
 hash sha512
!
!
crypto pki certificate chain TP-self-signed-2048003
 certificate self-signed 01
  	quit
!
!
memory free low-watermark processor 53379
!
!
spanning-tree mode rapid-pvst
spanning-tree portfast bpduguard default
spanning-tree extend system-id
!
username hq-admin privilege 15 secret 9 $9$4EKojIUav7tZh.$hzb6j2HGeT8RtvsHUdwoaUqdnk2hLFQkzm4mUjlFw4w
!         
vlan internal allocation policy ascending
!
!
!
!
!
interface Port-channel1
 description Uplink to HQ-OFFICE MLAG
 switchport trunk encapsulation dot1q
 switchport trunk native vlan 111
 switchport mode trunk
 ip arp inspection trust
 ip dhcp snooping trust
!
interface Ethernet0/0
 description Uplink to HQ-OFFICE-SW1
 switchport trunk encapsulation dot1q
 switchport trunk native vlan 111
 switchport mode trunk
 ip arp inspection trust
 channel-group 1 mode active
 ip dhcp snooping trust
!         
interface Ethernet0/1
 description Uplink to HQ-OFFICE-SW2
 switchport trunk encapsulation dot1q
 switchport trunk native vlan 111
 switchport mode trunk
 ip arp inspection trust
 channel-group 1 mode active
 ip dhcp snooping trust
!
interface Ethernet0/2
 description UNUSED-PORT
 switchport access vlan 999
 switchport mode access
 shutdown
!
interface Ethernet0/3
 description UNUSED-PORT
 switchport access vlan 999
 switchport mode access
 shutdown
!
interface Ethernet1/0
 description Link to HQ-FINANCES-PC
 switchport access vlan 50
 switchport mode access
 spanning-tree portfast
!
interface Ethernet1/1
 switchport access vlan 999
 switchport mode access
 shutdown
 spanning-tree portfast
!
interface Ethernet1/2
 description UNUSED-PORT
 switchport access vlan 999
 switchport mode access
 shutdown
!
interface Ethernet1/3
 description UNUSED-PORT
 switchport access vlan 999
 switchport mode access
 shutdown
!
interface Ethernet2/0
 description UNUSED-PORT
 switchport access vlan 999
 switchport mode access
 shutdown
!
interface Ethernet2/1
 description UNUSED-PORT
 switchport access vlan 999
 switchport mode access
 shutdown
!
interface Ethernet2/2
 description UNUSED-PORT
 switchport access vlan 999
 switchport mode access
 shutdown
!
interface Ethernet2/3
 description UNUSED-PORT
 switchport access vlan 999
 switchport mode access
 shutdown
!         
interface Ethernet3/0
 description UNUSED-PORT
 switchport access vlan 999
 switchport mode access
 shutdown
!
interface Ethernet3/1
 description UNUSED-PORT
 switchport access vlan 999
 switchport mode access
 shutdown
!
interface Ethernet3/2
 description UNUSED-PORT
 switchport access vlan 999
 switchport mode access
 shutdown
!
interface Ethernet3/3
 description UNUSED-PORT
 switchport access vlan 999
 switchport mode access
 shutdown 
!
interface Vlan1
 no ip address
 shutdown
!
interface Vlan10
 ip address 10.0.1.50 255.255.255.0
 no autostate
!
ip default-gateway 10.0.1.1
ip forward-protocol nd
!
!
ip tcp synwait-time 5
ip http server
ip http secure-server
ip ssh bulk-mode 131072
!
no logging btrace
!
!
!
control-plane
!
!
!
line con 0
 exec-timeout 0 0
 privilege level 15
 logging synchronous
line aux 0
 exec-timeout 0 0
 privilege level 15
 logging synchronous
line vty 0 4
 login local
 transport input ssh
!
ntp source Vlan10
ntp server 10.0.1.1 prefer
!
end
